-- 比赛计算器表
CREATE TABLE `match_calculator` (
    `match_id` INT NOT NULL COMMENT '比赛ID',
    `match_num` INT DEFAULT NULL COMMENT '比赛编号',
    `match_num_str` VARCHAR(50) DEFAULT NULL COMMENT '比赛编号字符串',
    `match_num_date` VARCHAR(20) DEFAULT NULL COMMENT '比赛编号日期',
    `match_date` VARCHAR(20) DEFAULT NULL COMMENT '比赛日期',
    `match_time` VARCHAR(20) DEFAULT NULL COMMENT '比赛时间',
    `match_week` VARCHAR(20) DEFAULT NULL COMMENT '比赛星期',

    -- 主队信息
    `home_team_id` INT DEFAULT NULL COMMENT '主队ID',
    `home_team_abb_name` VARCHAR(100) DEFAULT NULL COMMENT '主队简称',
    `home_team_abb_en_name` VARCHAR(100) DEFAULT NULL COMMENT '主队英文简称',
    `home_team_all_name` VARCHAR(200) DEFAULT NULL COMMENT '主队全称',
    `home_team_code` VARCHAR(50) DEFAULT NULL COMMENT '主队代码',
    `home_rank` VARCHAR(50) DEFAULT NULL COMMENT '主队排名',

    -- 客队信息
    `away_team_id` INT DEFAULT NULL COMMENT '客队ID',
    `away_team_abb_name` VARCHAR(100) DEFAULT NULL COMMENT '客队简称',
    `away_team_abb_en_name` VARCHAR(100) DEFAULT NULL COMMENT '客队英文简称',
    `away_team_all_name` VARCHAR(200) DEFAULT NULL COMMENT '客队全称',
    `away_team_code` VARCHAR(50) DEFAULT NULL COMMENT '客队代码',
    `away_rank` VARCHAR(50) DEFAULT NULL COMMENT '客队排名',

    -- 联赛信息
    `league_id` INT DEFAULT NULL COMMENT '联赛ID',
    `league_abb_name` VARCHAR(100) DEFAULT NULL COMMENT '联赛简称',
    `league_all_name` VARCHAR(200) DEFAULT NULL COMMENT '联赛全称',
    `league_code` VARCHAR(50) DEFAULT NULL COMMENT '联赛代码',

    -- 比赛状态
    `match_status` VARCHAR(50) DEFAULT NULL COMMENT '比赛状态',
    `sell_status` INT DEFAULT NULL COMMENT '销售状态',
    `back_color` VARCHAR(20) DEFAULT NULL COMMENT '背景颜色',
    `business_date` VARCHAR(20) DEFAULT NULL COMMENT '业务日期',
    `is_hide` INT DEFAULT 0 COMMENT '是否隐藏',
    `is_hot` INT DEFAULT 0 COMMENT '是否热门',
    `tax_date_no` VARCHAR(50) DEFAULT NULL COMMENT '税期编号',
    `betting_single` INT DEFAULT 0 COMMENT '让球过关单关',
    `betting_all_up` INT DEFAULT 0 COMMENT '让球过关串关',

    -- HAD 胜平负数据
    `had_h` VARCHAR(20) DEFAULT NULL COMMENT '胜平负-主胜赔率',
    `had_d` VARCHAR(20) DEFAULT NULL COMMENT '胜平负-平局赔率',
    `had_a` VARCHAR(20) DEFAULT NULL COMMENT '胜平负-客胜赔率',
    `had_hf` VARCHAR(20) DEFAULT NULL COMMENT '胜平负-主胜标识',
    `had_df` VARCHAR(20) DEFAULT NULL COMMENT '胜平负-平局标识',
    `had_af` VARCHAR(20) DEFAULT NULL COMMENT '胜平负-客胜标识',
    `had_update_date` VARCHAR(20) DEFAULT NULL COMMENT '胜平负-更新日期',
    `had_update_time` VARCHAR(20) DEFAULT NULL COMMENT '胜平负-更新时间',

    -- HHAD 让球胜平负数据
    `hhad_h` VARCHAR(20) DEFAULT NULL COMMENT '让球胜平负-主胜赔率',
    `hhad_d` VARCHAR(20) DEFAULT NULL COMMENT '让球胜平负-平局赔率',
    `hhad_a` VARCHAR(20) DEFAULT NULL COMMENT '让球胜平负-客胜赔率',
    `hhad_goal_line` VARCHAR(20) DEFAULT NULL COMMENT '让球胜平负-让球数',
    `hhad_goal_line_value` VARCHAR(20) DEFAULT NULL COMMENT '让球胜平负-让球数值',
    `hhad_hf` VARCHAR(20) DEFAULT NULL COMMENT '让球胜平负-主胜标识',
    `hhad_df` VARCHAR(20) DEFAULT NULL COMMENT '让球胜平负-平局标识',
    `hhad_af` VARCHAR(20) DEFAULT NULL COMMENT '让球胜平负-客胜标识',
    `hhad_update_date` VARCHAR(20) DEFAULT NULL COMMENT '让球胜平负-更新日期',
    `hhad_update_time` VARCHAR(20) DEFAULT NULL COMMENT '让球胜平负-更新时间',

    -- TTG 总进球数据
    `ttg_s0` VARCHAR(20) DEFAULT NULL COMMENT '总进球-0球赔率',
    `ttg_s1` VARCHAR(20) DEFAULT NULL COMMENT '总进球-1球赔率',
    `ttg_s2` VARCHAR(20) DEFAULT NULL COMMENT '总进球-2球赔率',
    `ttg_s3` VARCHAR(20) DEFAULT NULL COMMENT '总进球-3球赔率',
    `ttg_s4` VARCHAR(20) DEFAULT NULL COMMENT '总进球-4球赔率',
    `ttg_s5` VARCHAR(20) DEFAULT NULL COMMENT '总进球-5球赔率',
    `ttg_s6` VARCHAR(20) DEFAULT NULL COMMENT '总进球-6球赔率',
    `ttg_s7` VARCHAR(20) DEFAULT NULL COMMENT '总进球-7+球赔率',
    `ttg_update_date` VARCHAR(20) DEFAULT NULL COMMENT '总进球-更新日期',
    `ttg_update_time` VARCHAR(20) DEFAULT NULL COMMENT '总进球-更新时间',

    -- HAFU 半全场数据
    `hafu_hh` VARCHAR(20) DEFAULT NULL COMMENT '半全场-主主赔率',
    `hafu_hd` VARCHAR(20) DEFAULT NULL COMMENT '半全场-主平赔率',
    `hafu_ha` VARCHAR(20) DEFAULT NULL COMMENT '半全场-主客赔率',
    `hafu_dh` VARCHAR(20) DEFAULT NULL COMMENT '半全场-平主赔率',
    `hafu_dd` VARCHAR(20) DEFAULT NULL COMMENT '半全场-平平赔率',
    `hafu_da` VARCHAR(20) DEFAULT NULL COMMENT '半全场-平客赔率',
    `hafu_ah` VARCHAR(20) DEFAULT NULL COMMENT '半全场-客主赔率',
    `hafu_ad` VARCHAR(20) DEFAULT NULL COMMENT '半全场-客平赔率',
    `hafu_aa` VARCHAR(20) DEFAULT NULL COMMENT '半全场-客客赔率',
    `hafu_hhf` VARCHAR(20) DEFAULT NULL COMMENT '半全场-主主标识',
    `hafu_hdf` VARCHAR(20) DEFAULT NULL COMMENT '半全场-主平标识',
    `hafu_haf` VARCHAR(20) DEFAULT NULL COMMENT '半全场-主客标识',
    `hafu_dhf` VARCHAR(20) DEFAULT NULL COMMENT '半全场-平主标识',
    `hafu_ddf` VARCHAR(20) DEFAULT NULL COMMENT '半全场-平平标识',
    `hafu_daf` VARCHAR(20) DEFAULT NULL COMMENT '半全场-平客标识',
    `hafu_ahf` VARCHAR(20) DEFAULT NULL COMMENT '半全场-客主标识',
    `hafu_adf` VARCHAR(20) DEFAULT NULL COMMENT '半全场-客平标识',
    `hafu_aaf` VARCHAR(20) DEFAULT NULL COMMENT '半全场-客客标识',
    `hafu_update_date` VARCHAR(20) DEFAULT NULL COMMENT '半全场-更新日期',
    `hafu_update_time` VARCHAR(20) DEFAULT NULL COMMENT '半全场-更新时间',

    -- CRS 比分数据
    `crs_s00s00` VARCHAR(20) DEFAULT NULL COMMENT '比分-0:0赔率',
    `crs_s00s01` VARCHAR(20) DEFAULT NULL COMMENT '比分-0:1赔率',
    `crs_s00s02` VARCHAR(20) DEFAULT NULL COMMENT '比分-0:2赔率',
    `crs_s00s03` VARCHAR(20) DEFAULT NULL COMMENT '比分-0:3赔率',
    `crs_s00s04` VARCHAR(20) DEFAULT NULL COMMENT '比分-0:4赔率',
    `crs_s00s05` VARCHAR(20) DEFAULT NULL COMMENT '比分-0:5+赔率',
    `crs_s01s00` VARCHAR(20) DEFAULT NULL COMMENT '比分-1:0赔率',
    `crs_s01s01` VARCHAR(20) DEFAULT NULL COMMENT '比分-1:1赔率',
    `crs_s01s02` VARCHAR(20) DEFAULT NULL COMMENT '比分-1:2赔率',
    `crs_s01s03` VARCHAR(20) DEFAULT NULL COMMENT '比分-1:3赔率',
    `crs_s01s04` VARCHAR(20) DEFAULT NULL COMMENT '比分-1:4赔率',
    `crs_s01s05` VARCHAR(20) DEFAULT NULL COMMENT '比分-1:5+赔率',
    `crs_s02s00` VARCHAR(20) DEFAULT NULL COMMENT '比分-2:0赔率',
    `crs_s02s01` VARCHAR(20) DEFAULT NULL COMMENT '比分-2:1赔率',
    `crs_s02s02` VARCHAR(20) DEFAULT NULL COMMENT '比分-2:2赔率',
    `crs_s02s03` VARCHAR(20) DEFAULT NULL COMMENT '比分-2:3赔率',
    `crs_s02s04` VARCHAR(20) DEFAULT NULL COMMENT '比分-2:4赔率',
    `crs_s02s05` VARCHAR(20) DEFAULT NULL COMMENT '比分-2:5+赔率',
    `crs_s03s00` VARCHAR(20) DEFAULT NULL COMMENT '比分-3:0赔率',
    `crs_s03s01` VARCHAR(20) DEFAULT NULL COMMENT '比分-3:1赔率',
    `crs_s03s02` VARCHAR(20) DEFAULT NULL COMMENT '比分-3:2赔率',
    `crs_s03s03` VARCHAR(20) DEFAULT NULL COMMENT '比分-3:3赔率',
    `crs_s04s00` VARCHAR(20) DEFAULT NULL COMMENT '比分-4:0赔率',
    `crs_s04s01` VARCHAR(20) DEFAULT NULL COMMENT '比分-4:1赔率',
    `crs_s04s02` VARCHAR(20) DEFAULT NULL COMMENT '比分-4:2赔率',
    `crs_s05s00` VARCHAR(20) DEFAULT NULL COMMENT '比分-5+:0赔率',
    `crs_s05s01` VARCHAR(20) DEFAULT NULL COMMENT '比分-5+:1赔率',
    `crs_s05s02` VARCHAR(20) DEFAULT NULL COMMENT '比分-5+:2赔率',
    `crs_s1sh` VARCHAR(20) DEFAULT NULL COMMENT '比分-半场主胜赔率',
    `crs_s1sd` VARCHAR(20) DEFAULT NULL COMMENT '比分-半场平局赔率',
    `crs_s1sa` VARCHAR(20) DEFAULT NULL COMMENT '比分-半场客胜赔率',
    `crs_update_date` VARCHAR(20) DEFAULT NULL COMMENT '比分-更新日期',
    `crs_update_time` VARCHAR(20) DEFAULT NULL COMMENT '比分-更新时间',

    -- 基础字段
    `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `deleted` INT DEFAULT 0 COMMENT '逻辑删除符',

    PRIMARY KEY (`match_id`),
    KEY `idx_match_date` (`match_date`),
    KEY `idx_league_id` (`league_id`),
    KEY `idx_home_team_id` (`home_team_id`),
    KEY `idx_away_team_id` (`away_team_id`),
    KEY `idx_match_status` (`match_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='比赛计算器表';
