package cn.xingxing.common.config;

import lombok.Data;
import org.springframework.boot.context.properties.ConfigurationProperties;
import org.springframework.stereotype.Component;

@Data
@Component
@ConfigurationProperties(prefix = "football.api")
public class FootballApiConfig {

    // 彩票API
    private String matchListUrl = "https://webapi.sporttery.cn/gateway/uniform/fb/getMatchDataPageListV1.qry?method=concern";
    private String fixedBonusUrl = "https://webapi.sporttery.cn/gateway/uniform/football/getFixedBonusV1.qry?clientCode=3001&matchId=";
    private String searchOddsUrl = "https://webapi.sporttery.cn/gateway/uniform/football/searchOddsV1.qry?channel=c&type=&single=0&h=%s&a=%s&d=%s";
    private String searchOddsUrl2 = "https://webapi.sporttery.cn/gateway/uniform/football/searchOddsV1.qry?channel=c&type=&single=1&h=%s&a=%s&d=%s";
    //历史交锋
    private String resultHistoryUrl = "https://webapi.sporttery.cn/gateway/uniform/football/getResultHistoryV1.qry?" +
            "sportteryMatchId=%s&termLimits=10&tournamentFlag=0&homeAwayFlag=0";
    //比赛近况
    private String matchHistoryUrl =
            "https://webapi.sporttery.cn/gateway/uniform/football/getMatchResultV1.qry?sportteryMatchId=%s&termLimits=5&tournamentFlag=0&homeAwayFlag=0";
    //比赛结果
    private String matchResultUrl = "https://webapi.sporttery.cn/gateway/uniform/fb/getMatchDataPageListV1.qry?" +
            "method=result&pageNo=1&pageType=0&pageSize=300";

    private String matchResultDetailUrl = "https://webapi.sporttery.cn/gateway/uniform/fb/getMatchGeneral.qry?matchId=%s&matchStatus=11";
    /**
     * {
     *     "dataFrom": "",
     *     "emptyFlag": false,
     *     "errorCode": "0",
     *     "errorMessage": "处理成功",
     *     "success": true,
     *     "value": [
     *         {
     *             "awayTeamAbbName": "瑞士",
     *             "awayTeamAllName": "瑞士",
     *             "backColor": "005E5E",
     *             "cancelStatus": "",
     *             "eventList": [],
     *             "homeTeamAbbName": "挪威",
     *             "homeTeamAllName": "挪威",
     *             "leagueAbbName": "国际赛",
     *             "leagueAllName": "国际赛",
     *             "leagueId": "39",
     *             "matchDate": "2026-04-01",
     *             "matchId": 2038721,
     *             "matchMinute": "",
     *             "matchMinuteExtra": "",
     *             "matchNum": 2003,
     *             "matchNumStr": "",
     *             "matchPhaseTc": "",
     *             "matchPhaseTcName": "",
     *             "matchResultList": [],
     *             "matchStatus": "11",
     *             "matchStatusName": "已完成",
     *             "matchTime": "00:00:00",
     *             "poolList": [],
     *             "sectionsExtra": "",
     *             "sectionsNo1": "0:0",
     *             "sectionsNo999": "0:0",
     *             "sectionsPenalty": "",
     *             "weekday": ""
     *         },
     *         {
     *             "awayTeamAbbName": "斯洛文尼",
     *             "awayTeamAllName": "斯洛文尼亚",
     *             "backColor": "005E5E",
     *             "cancelStatus": "",
     *             "eventList": [],
     *             "homeTeamAbbName": "黑山",
     *             "homeTeamAllName": "黑山",
     *             "leagueAbbName": "国际赛",
     *             "leagueAllName": "国际赛",
     *             "leagueId": "39",
     *             "matchDate": "2026-04-01",
     *             "matchId": 2038722,
     *             "matchMinute": "",
     *             "matchMinuteExtra": "",
     *             "matchNum": 2004,
     *             "matchNumStr": "",
     *             "matchPhaseTc": "",
     *             "matchPhaseTcName": "",
     *             "matchResultList": [],
     *             "matchStatus": "11",
     *             "matchStatusName": "已完成",
     *             "matchTime": "00:00:00",
     *             "poolList": [],
     *             "sectionsExtra": "",
     *             "sectionsNo1": "2:1",
     *             "sectionsNo999": "2:3",
     *             "sectionsPenalty": "",
     *             "weekday": ""
     *         },
     *         {
     *             "awayTeamAbbName": "希腊",
     *             "awayTeamAllName": "希腊",
     *             "backColor": "005E5E",
     *             "cancelStatus": "",
     *             "eventList": [],
     *             "homeTeamAbbName": "匈牙利",
     *             "homeTeamAllName": "匈牙利",
     *             "leagueAbbName": "国际赛",
     *             "leagueAllName": "国际赛",
     *             "leagueId": "39",
     *             "matchDate": "2026-04-01",
     *             "matchId": 2038723,
     *             "matchMinute": "",
     *             "matchMinuteExtra": "",
     *             "matchNum": 2005,
     *             "matchNumStr": "",
     *             "matchPhaseTc": "",
     *             "matchPhaseTcName": "",
     *             "matchResultList": [],
     *             "matchStatus": "11",
     *             "matchStatusName": "已完成",
     *             "matchTime": "01:00:00",
     *             "poolList": [],
     *             "sectionsExtra": "",
     *             "sectionsNo1": "0:0",
     *             "sectionsNo999": "0:0",
     *             "sectionsPenalty": "",
     *             "weekday": ""
     *         },
     *         {
     *             "awayTeamAbbName": "巴拿马",
     *             "awayTeamAllName": "巴拿马",
     *             "backColor": "005E5E",
     *             "cancelStatus": "",
     *             "eventList": [],
     *             "homeTeamAbbName": "南非",
     *             "homeTeamAllName": "南非",
     *             "leagueAbbName": "国际赛",
     *             "leagueAllName": "国际赛",
     *             "leagueId": "39",
     *             "matchDate": "2026-04-01",
     *             "matchId": 2038724,
     *             "matchMinute": "",
     *             "matchMinuteExtra": "",
     *             "matchNum": 2006,
     *             "matchNumStr": "",
     *             "matchPhaseTc": "",
     *             "matchPhaseTcName": "",
     *             "matchResultList": [],
     *             "matchStatus": "11",
     *             "matchStatusName": "已完成",
     *             "matchTime": "01:30:00",
     *             "poolList": [],
     *             "sectionsExtra": "",
     *             "sectionsNo1": "0:0",
     *             "sectionsNo999": "1:2",
     *             "sectionsPenalty": "",
     *             "weekday": ""
     *         },
     *         {
     *             "awayTeamAbbName": "巴拉圭",
     *             "awayTeamAllName": "巴拉圭",
     *             "backColor": "005E5E",
     *             "cancelStatus": "",
     *             "eventList": [],
     *             "homeTeamAbbName": "摩洛哥",
     *             "homeTeamAllName": "摩洛哥",
     *             "leagueAbbName": "国际赛",
     *             "leagueAllName": "国际赛",
     *             "leagueId": "39",
     *             "matchDate": "2026-04-01",
     *             "matchId": 2038725,
     *             "matchMinute": "",
     *             "matchMinuteExtra": "",
     *             "matchNum": 2007,
     *             "matchNumStr": "",
     *             "matchPhaseTc": "",
     *             "matchPhaseTcName": "",
     *             "matchResultList": [],
     *             "matchStatus": "11",
     *             "matchStatusName": "已完成",
     *             "matchTime": "02:00:00",
     *             "poolList": [],
     *             "sectionsExtra": "",
     *             "sectionsNo1": "0:0",
     *             "sectionsNo999": "2:1",
     *             "sectionsPenalty": "",
     *             "weekday": ""
     *         },
     *         {
     *             "awayTeamAbbName": "乌拉圭",
     *             "awayTeamAllName": "乌拉圭",
     *             "backColor": "005E5E",
     *             "cancelStatus": "",
     *             "eventList": [],
     *             "homeTeamAbbName": "阿尔及利",
     *             "homeTeamAllName": "阿尔及利亚",
     *             "leagueAbbName": "国际赛",
     *             "leagueAllName": "国际赛",
     *             "leagueId": "39",
     *             "matchDate": "2026-04-01",
     *             "matchId": 2038726,
     *             "matchMinute": "",
     *             "matchMinuteExtra": "",
     *             "matchNum": 2008,
     *             "matchNumStr": "",
     *             "matchPhaseTc": "",
     *             "matchPhaseTcName": "",
     *             "matchResultList": [],
     *             "matchStatus": "11",
     *             "matchStatusName": "已完成",
     *             "matchTime": "02:30:00",
     *             "poolList": [],
     *             "sectionsExtra": "",
     *             "sectionsNo1": "0:0",
     *             "sectionsNo999": "0:0",
     *             "sectionsPenalty": "",
     *             "weekday": ""
     *         },
     *         {
     *             "awayTeamAbbName": "科特迪瓦",
     *             "awayTeamAllName": "科特迪瓦",
     *             "backColor": "005E5E",
     *             "cancelStatus": "",
     *             "eventList": [],
     *             "homeTeamAbbName": "苏格兰",
     *             "homeTeamAllName": "苏格兰",
     *             "leagueAbbName": "国际赛",
     *             "leagueAllName": "国际赛",
     *             "leagueId": "39",
     *             "matchDate": "2026-04-01",
     *             "matchId": 2038727,
     *             "matchMinute": "",
     *             "matchMinuteExtra": "",
     *             "matchNum": 2009,
     *             "matchNumStr": "",
     *             "matchPhaseTc": "",
     *             "matchPhaseTcName": "",
     *             "matchResultList": [],
     *             "matchStatus": "11",
     *             "matchStatusName": "已完成",
     *             "matchTime": "02:30:00",
     *             "poolList": [],
     *             "sectionsExtra": "",
     *             "sectionsNo1": "0:1",
     *             "sectionsNo999": "0:1",
     *             "sectionsPenalty": "",
     *             "weekday": ""
     *         },
     *         {
     *             "awayTeamAbbName": "厄瓜多尔",
     *             "awayTeamAllName": "厄瓜多尔",
     *             "backColor": "005E5E",
     *             "cancelStatus": "",
     *             "eventList": [],
     *             "homeTeamAbbName": "荷兰",
     *             "homeTeamAllName": "荷兰",
     *             "leagueAbbName": "国际赛",
     *             "leagueAllName": "国际赛",
     *             "leagueId": "39",
     *             "matchDate": "2026-04-01",
     *             "matchId": 2038728,
     *             "matchMinute": "",
     *             "matchMinuteExtra": "",
     *             "matchNum": 2010,
     *             "matchNumStr": "",
     *             "matchPhaseTc": "",
     *             "matchPhaseTcName": "",
     *             "matchResultList": [],
     *             "matchStatus": "11",
     *             "matchStatusName": "已完成",
     *             "matchTime": "02:45:00",
     *             "poolList": [],
     *             "sectionsExtra": "",
     *             "sectionsNo1": "1:1",
     *             "sectionsNo999": "1:1",
     *             "sectionsPenalty": "",
     *             "weekday": ""
     *         },
     *         {
     *             "awayTeamAbbName": "日本",
     *             "awayTeamAllName": "日本",
     *             "backColor": "005E5E",
     *             "cancelStatus": "",
     *             "eventList": [],
     *             "homeTeamAbbName": "英格兰",
     *             "homeTeamAllName": "英格兰",
     *             "leagueAbbName": "国际赛",
     *             "leagueAllName": "国际赛",
     *             "leagueId": "39",
     *             "matchDate": "2026-04-01",
     *             "matchId": 2038729,
     *             "matchMinute": "",
     *             "matchMinuteExtra": "",
     *             "matchNum": 2011,
     *             "matchNumStr": "",
     *             "matchPhaseTc": "",
     *             "matchPhaseTcName": "",
     *             "matchResultList": [],
     *             "matchStatus": "11",
     *             "matchStatusName": "已完成",
     *             "matchTime": "02:45:00",
     *             "poolList": [],
     *             "sectionsExtra": "",
     *             "sectionsNo1": "0:1",
     *             "sectionsNo999": "0:1",
     *             "sectionsPenalty": "",
     *             "weekday": ""
     *         },
     *         {
     *             "awayTeamAbbName": "韩国",
     *             "awayTeamAllName": "韩国",
     *             "backColor": "005E5E",
     *             "cancelStatus": "",
     *             "eventList": [],
     *             "homeTeamAbbName": "奥地利",
     *             "homeTeamAllName": "奥地利",
     *             "leagueAbbName": "国际赛",
     *             "leagueAllName": "国际赛",
     *             "leagueId": "39",
     *             "matchDate": "2026-04-01",
     *             "matchId": 2038730,
     *             "matchMinute": "",
     *             "matchMinuteExtra": "",
     *             "matchNum": 2012,
     *             "matchNumStr": "",
     *             "matchPhaseTc": "",
     *             "matchPhaseTcName": "",
     *             "matchResultList": [],
     *             "matchStatus": "11",
     *             "matchStatusName": "已完成",
     *             "matchTime": "02:45:00",
     *             "poolList": [],
     *             "sectionsExtra": "",
     *             "sectionsNo1": "0:0",
     *             "sectionsNo999": "1:0",
     *             "sectionsPenalty": "",
     *             "weekday": ""
     *         },
     *         {
     *             "awayTeamAbbName": "土耳其",
     *             "awayTeamAllName": "土耳其",
     *             "backColor": "660000",
     *             "cancelStatus": "",
     *             "eventList": [],
     *             "homeTeamAbbName": "科索沃",
     *             "homeTeamAllName": "科索沃",
     *             "leagueAbbName": "世预赛",
     *             "leagueAllName": "世界杯预选赛",
     *             "leagueId": "73",
     *             "matchDate": "2026-04-01",
     *             "matchId": 2038731,
     *             "matchMinute": "",
     *             "matchMinuteExtra": "",
     *             "matchNum": 2013,
     *             "matchNumStr": "",
     *             "matchPhaseTc": "",
     *             "matchPhaseTcName": "",
     *             "matchResultList": [],
     *             "matchStatus": "11",
     *             "matchStatusName": "已完成",
     *             "matchTime": "02:45:00",
     *             "poolList": [],
     *             "sectionsExtra": "",
     *             "sectionsNo1": "0:0",
     *             "sectionsNo999": "0:1",
     *             "sectionsPenalty": "",
     *             "weekday": ""
     *         },
     *         {
     *             "awayTeamAbbName": "波兰",
     *             "awayTeamAllName": "波兰",
     *             "backColor": "660000",
     *             "cancelStatus": "",
     *             "eventList": [],
     *             "homeTeamAbbName": "瑞典",
     *             "homeTeamAllName": "瑞典",
     *             "leagueAbbName": "世预赛",
     *             "leagueAllName": "世界杯预选赛",
     *             "leagueId": "73",
     *             "matchDate": "2026-04-01",
     *             "matchId": 2038732,
     *             "matchMinute": "",
     *             "matchMinuteExtra": "",
     *             "matchNum": 2014,
     *             "matchNumStr": "",
     *             "matchPhaseTc": "",
     *             "matchPhaseTcName": "",
     *             "matchResultList": [],
     *             "matchStatus": "11",
     *             "matchStatusName": "已完成",
     *             "matchTime": "02:45:00",
     *             "poolList": [],
     *             "sectionsExtra": "",
     *             "sectionsNo1": "2:1",
     *             "sectionsNo999": "3:2",
     *             "sectionsPenalty": "",
     *             "weekday": ""
     *         },
     *         {
     *             "awayTeamAbbName": "意大利",
     *             "awayTeamAllName": "意大利",
     *             "backColor": "660000",
     *             "cancelStatus": "",
     *             "eventList": [],
     *             "homeTeamAbbName": "波黑",
     *             "homeTeamAllName": "波黑",
     *             "leagueAbbName": "世预赛",
     *             "leagueAllName": "世界杯预选赛",
     *             "leagueId": "73",
     *             "matchDate": "2026-04-01",
     *             "matchId": 2038733,
     *             "matchMinute": "",
     *             "matchMinuteExtra": "",
     *             "matchNum": 2015,
     *             "matchNumStr": "",
     *             "matchPhaseTc": "",
     *             "matchPhaseTcName": "",
     *             "matchResultList": [],
     *             "matchStatus": "11",
     *             "matchStatusName": "已完成",
     *             "matchTime": "02:45:00",
     *             "poolList": [],
     *             "sectionsExtra": "",
     *             "sectionsNo1": "0:1",
     *             "sectionsNo999": "1:1",
     *             "sectionsPenalty": "",
     *             "weekday": ""
     *         },
     *         {
     *             "awayTeamAbbName": "丹麦",
     *             "awayTeamAllName": "丹麦",
     *             "backColor": "660000",
     *             "cancelStatus": "",
     *             "eventList": [],
     *             "homeTeamAbbName": "捷克",
     *             "homeTeamAllName": "捷克",
     *             "leagueAbbName": "世预赛",
     *             "leagueAllName": "世界杯预选赛",
     *             "leagueId": "73",
     *             "matchDate": "2026-04-01",
     *             "matchId": 2038734,
     *             "matchMinute": "",
     *             "matchMinuteExtra": "",
     *             "matchNum": 2016,
     *             "matchNumStr": "",
     *             "matchPhaseTc": "",
     *             "matchPhaseTcName": "",
     *             "matchResultList": [],
     *             "matchStatus": "11",
     *             "matchStatusName": "已完成",
     *             "matchTime": "02:45:00",
     *             "poolList": [],
     *             "sectionsExtra": "",
     *             "sectionsNo1": "1:0",
     *             "sectionsNo999": "1:1",
     *             "sectionsPenalty": "",
     *             "weekday": ""
     *         },
     *         {
     *             "awayTeamAbbName": "埃及",
     *             "awayTeamAllName": "埃及",
     *             "backColor": "005E5E",
     *             "cancelStatus": "",
     *             "eventList": [],
     *             "homeTeamAbbName": "西班牙",
     *             "homeTeamAllName": "西班牙",
     *             "leagueAbbName": "国际赛",
     *             "leagueAllName": "国际赛",
     *             "leagueId": "39",
     *             "matchDate": "2026-04-01",
     *             "matchId": 2038735,
     *             "matchMinute": "",
     *             "matchMinuteExtra": "",
     *             "matchNum": 2017,
     *             "matchNumStr": "",
     *             "matchPhaseTc": "",
     *             "matchPhaseTcName": "",
     *             "matchResultList": [],
     *             "matchStatus": "11",
     *             "matchStatusName": "已完成",
     *             "matchTime": "03:00:00",
     *             "poolList": [],
     *             "sectionsExtra": "",
     *             "sectionsNo1": "0:0",
     *             "sectionsNo999": "0:0",
     *             "sectionsPenalty": "",
     *             "weekday": ""
     *         },
     *         {
     *             "awayTeamAbbName": "牙买加",
     *             "awayTeamAllName": "牙买加",
     *             "backColor": "660000",
     *             "cancelStatus": "",
     *             "eventList": [],
     *             "homeTeamAbbName": "刚果金",
     *             "homeTeamAllName": "刚果(金)",
     *             "leagueAbbName": "世预赛",
     *             "leagueAllName": "世界杯预选赛",
     *             "leagueId": "73",
     *             "matchDate": "2026-04-01",
     *             "matchId": 2038736,
     *             "matchMinute": "",
     *             "matchMinuteExtra": "",
     *             "matchNum": 2018,
     *             "matchNumStr": "",
     *             "matchPhaseTc": "",
     *             "matchPhaseTcName": "",
     *             "matchResultList": [],
     *             "matchStatus": "11",
     *             "matchStatusName": "已完成",
     *             "matchTime": "05:00:00",
     *             "poolList": [],
     *             "sectionsExtra": "",
     *             "sectionsNo1": "0:0",
     *             "sectionsNo999": "0:0",
     *             "sectionsPenalty": "",
     *             "weekday": ""
     *         },
     *         {
     *             "awayTeamAbbName": "葡萄牙",
     *             "awayTeamAllName": "葡萄牙",
     *             "backColor": "005E5E",
     *             "cancelStatus": "",
     *             "eventList": [],
     *             "homeTeamAbbName": "美国",
     *             "homeTeamAllName": "美国",
     *             "leagueAbbName": "国际赛",
     *             "leagueAllName": "国际赛",
     *             "leagueId": "39",
     *             "matchDate": "2026-04-01",
     *             "matchId": 2038737,
     *             "matchMinute": "",
     *             "matchMinuteExtra": "",
     *             "matchNum": 2019,
     *             "matchNumStr": "",
     *             "matchPhaseTc": "",
     *             "matchPhaseTcName": "",
     *             "matchResultList": [],
     *             "matchStatus": "11",
     *             "matchStatusName": "已完成",
     *             "matchTime": "07:00:00",
     *             "poolList": [],
     *             "sectionsExtra": "",
     *             "sectionsNo1": "0:1",
     *             "sectionsNo999": "0:2",
     *             "sectionsPenalty": "",
     *             "weekday": ""
     *         },
     *         {
     *             "awayTeamAbbName": "突尼斯",
     *             "awayTeamAllName": "突尼斯",
     *             "backColor": "005E5E",
     *             "cancelStatus": "",
     *             "eventList": [],
     *             "homeTeamAbbName": "加拿大",
     *             "homeTeamAllName": "加拿大",
     *             "leagueAbbName": "国际赛",
     *             "leagueAllName": "国际赛",
     *             "leagueId": "39",
     *             "matchDate": "2026-04-01",
     *             "matchId": 2038738,
     *             "matchMinute": "59",
     *             "matchMinuteExtra": "",
     *             "matchNum": 2020,
     *             "matchNumStr": "",
     *             "matchPhaseTc": "2",
     *             "matchPhaseTcName": "季后赛",
     *             "matchResultList": [],
     *             "matchStatus": "5",
     *             "matchStatusName": "直播中",
     *             "matchTime": "07:30:00",
     *             "poolList": [],
     *             "sectionsExtra": "",
     *             "sectionsNo1": "0:0",
     *             "sectionsNo999": "0:0",
     *             "sectionsPenalty": "",
     *             "weekday": ""
     *         },
     *         {
     *             "awayTeamAbbName": "克罗地亚",
     *             "awayTeamAllName": "克罗地亚",
     *             "backColor": "005E5E",
     *             "cancelStatus": "",
     *             "eventList": [
     *                 {
     *                     "eventCode": "G",
     *                     "eventTc": "goals",
     *                     "matchMinute": "47",
     *                     "matchMinuteExtra": "",
     *                     "matchPhaseTc": "1",
     *                     "personEnName": "Danilo",
     *                     "teamType": "home",
     *                     "uniformNo": "18"
     *                 },
     *                 {
     *                     "eventCode": "G",
     *                     "eventTc": "goals",
     *                     "matchMinute": "84",
     *                     "matchMinuteExtra": "",
     *                     "matchPhaseTc": "2",
     *                     "personEnName": "马耶尔",
     *                     "teamType": "away",
     *                     "uniformNo": "7"
     *                 },
     *                 {
     *                     "eventCode": "PG",
     *                     "eventTc": "goals",
     *                     "matchMinute": "88",
     *                     "matchMinuteExtra": "",
     *                     "matchPhaseTc": "2",
     *                     "personEnName": "蒂亚戈",
     *                     "teamType": "home",
     *                     "uniformNo": "21"
     *                 },
     *                 {
     *                     "eventCode": "G",
     *                     "eventTc": "goals",
     *                     "matchMinute": "92",
     *                     "matchMinuteExtra": "",
     *                     "matchPhaseTc": "2",
     *                     "personEnName": "马蒂内利",
     *                     "teamType": "home",
     *                     "uniformNo": "22"
     *                 }
     *             ],
     *             "homeTeamAbbName": "巴西",
     *             "homeTeamAllName": "巴西",
     *             "leagueAbbName": "国际赛",
     *             "leagueAllName": "国际赛",
     *             "leagueId": "39",
     *             "matchDate": "2026-04-01",
     *             "matchId": 2038739,
     *             "matchMinute": "101",
     *             "matchMinuteExtra": "",
     *             "matchNum": 2021,
     *             "matchNumStr": "",
     *             "matchPhaseTc": "14",
     *             "matchPhaseTcName": "比赛结束",
     *             "matchResultList": [],
     *             "matchStatus": "6",
     *             "matchStatusName": "直播结束",
     *             "matchTime": "08:00:00",
     *             "poolList": [],
     *             "sectionsExtra": "",
     *             "sectionsNo1": "1:0",
     *             "sectionsNo999": "3:1",
     *             "sectionsPenalty": "",
     *             "weekday": ""
     *         },
     *         {
     *             "awayTeamAbbName": "比利时",
     *             "awayTeamAllName": "比利时",
     *             "backColor": "005E5E",
     *             "cancelStatus": "",
     *             "eventList": [
     *                 {
     *                     "eventCode": "G",
     *                     "eventTc": "goals",
     *                     "matchMinute": "19",
     *                     "matchMinuteExtra": "",
     *                     "matchPhaseTc": "1",
     *                     "personEnName": "桑切斯",
     *                     "teamType": "home",
     *                     "uniformNo": "2"
     *                 },
     *                 {
     *                     "eventCode": "G",
     *                     "eventTc": "goals",
     *                     "matchMinute": "46",
     *                     "matchMinuteExtra": "",
     *                     "matchPhaseTc": "2",
     *                     "personEnName": "卢凯巴基奥",
     *                     "teamType": "away",
     *                     "uniformNo": "14"
     *                 }
     *             ],
     *             "homeTeamAbbName": "墨西哥",
     *             "homeTeamAllName": "墨西哥",
     *             "leagueAbbName": "国际赛",
     *             "leagueAllName": "国际赛",
     *             "leagueId": "39",
     *             "matchDate": "2026-04-01",
     *             "matchId": 2038740,
     *             "matchMinute": "65",
     *             "matchMinuteExtra": "",
     *             "matchNum": 2022,
     *             "matchNumStr": "",
     *             "matchPhaseTc": "2",
     *             "matchPhaseTcName": "季后赛",
     *             "matchResultList": [],
     *             "matchStatus": "5",
     *             "matchStatusName": "直播中",
     *             "matchTime": "09:00:00",
     *             "poolList": [],
     *             "sectionsExtra": "",
     *             "sectionsNo1": "1:0",
     *             "sectionsNo999": "1:1",
     *             "sectionsPenalty": "",
     *             "weekday": ""
     *         },
     *         {
     *             "awayTeamAbbName": "玻利维亚",
     *             "awayTeamAllName": "玻利维亚",
     *             "backColor": "660000",
     *             "cancelStatus": "",
     *             "eventList": [],
     *             "homeTeamAbbName": "伊拉克",
     *             "homeTeamAllName": "伊拉克",
     *             "leagueAbbName": "世预赛",
     *             "leagueAllName": "世界杯预选赛",
     *             "leagueId": "73",
     *             "matchDate": "2026-04-01",
     *             "matchId": 2038741,
     *             "matchMinute": "0",
     *             "matchMinuteExtra": "",
     *             "matchNum": 2023,
     *             "matchNumStr": "",
     *             "matchPhaseTc": "16",
     *             "matchPhaseTcName": "赛前",
     *             "matchResultList": [],
     *             "matchStatus": "4",
     *             "matchStatusName": "未开播",
     *             "matchTime": "11:00:00",
     *             "poolList": [],
     *             "sectionsExtra": "",
     *             "sectionsNo1": "",
     *             "sectionsNo999": "",
     *             "sectionsPenalty": "",
     *             "weekday": ""
     *         },
     *         {
     *             "awayTeamAbbName": "清水鼓动",
     *             "awayTeamAllName": "清水鼓动",
     *             "backColor": "009900",
     *             "cancelStatus": "",
     *             "eventList": [],
     *             "homeTeamAbbName": "神户胜利",
     *             "homeTeamAllName": "神户胜利船",
     *             "leagueAbbName": "日职",
     *             "leagueAllName": "日本职业联赛",
     *             "leagueId": "42",
     *             "matchDate": "2026-04-01",
     *             "matchId": 2038742,
     *             "matchMinute": "0",
     *             "matchMinuteExtra": "",
     *             "matchNum": 3001,
     *             "matchNumStr": "",
     *             "matchPhaseTc": "16",
     *             "matchPhaseTcName": "赛前",
     *             "matchResultList": [],
     *             "matchStatus": "4",
     *             "matchStatusName": "未开播",
     *             "matchTime": "18:00:00",
     *             "poolList": [],
     *             "sectionsExtra": "",
     *             "sectionsNo1": "",
     *             "sectionsNo999": "",
     *             "sectionsPenalty": "",
     *             "weekday": ""
     *         },
     *         {
     *             "awayTeamAbbName": "东京FC",
     *             "awayTeamAllName": "东京FC",
     *             "backColor": "009900",
     *             "cancelStatus": "",
     *             "eventList": [],
     *             "homeTeamAbbName": "町田泽维",
     *             "homeTeamAllName": "町田泽维亚",
     *             "leagueAbbName": "日职",
     *             "leagueAllName": "日本职业联赛",
     *             "leagueId": "42",
     *             "matchDate": "2026-04-01",
     *             "matchId": 2038743,
     *             "matchMinute": "0",
     *             "matchMinuteExtra": "",
     *             "matchNum": 3002,
     *             "matchNumStr": "",
     *             "matchPhaseTc": "16",
     *             "matchPhaseTcName": "赛前",
     *             "matchResultList": [],
     *             "matchStatus": "4",
     *             "matchStatusName": "未开播",
     *             "matchTime": "18:00:00",
     *             "poolList": [],
     *             "sectionsExtra": "",
     *             "sectionsNo1": "",
     *             "sectionsNo999": "",
     *             "sectionsPenalty": "",
     *             "weekday": ""
     *         }
     *     ]
     * }
     */

    private String liveUrl = "https://webapi.sporttery.cn/gateway/uniform/fb/getMatchLiveV1.qry?matchIds=%s&eventTc=goals,penalty_shootout&method=live";

    private String matchCalculatorUrl= "https://webapi.sporttery.cn/gateway/uniform/football/getMatchCalculatorV1.qry?channel=c";
    //比赛特征
    private String matchFeatureUrl= "https://webapi.sporttery.cn/gateway/uniform/football/getMatchFeatureV1.qry?termLimits=10&sportteryMatchId=%s";
    //射手榜
    private String player = "https://webapi.sporttery.cn/gateway/uniform/football/getMatchPlayerV1.qry?sportteryMatchId=2036289&termLimits=3";
    //伤停信息
    private String injurySuspension = "https://webapi.sporttery.cn/gateway/uniform/football/getInjurySuspensionV1.qry?sportteryMatchId=2036289";
    // 飞书Webhook
    private String feishuWebhookUrl = "https://open.feishu.cn/open-apis/bot/v2/hook/a553e701-25e0-4e58-ad26-920fde4c2631";

    // 定时任务配置
    private long scheduleInitialDelay = 10000;
    private long scheduleFixedDelay = 14400000;

    // 超时配置
    private int httpConnectTimeout = 20000;
    private int httpReadTimeout = 50000;
}